---
/offline_process/vo:
  ros__parameters:
    use_sim_time: true
    GNSSFGO:
      verbose: false
      offlineProcess: true
      useIMUAsTimeReference: false
      bufferSize: 10
      optFrequency: 10 #in Hz
      stateFrequency: 10
      calcErrorOnOpt: true
      cleanIMUonInit: true    # set this flag to clean the imu data before the timestamp of the initializing state
      useHeaderTimestamp: true
      calibGravity: true

      Initialization:
        initSigmaX: [ 10., 10., 10., 0.1, 0.1, 0.1 ] #first 3 for Rot in degree, other for translation in m
        initSigmaV: [ 1000., 1000., 1000. ]
        initSigmaW: [ 0.05, 0.05, 0.05 ]
        initSigmaB: [ 0.5, 0.5, 0.5, 0.05, 0.05, 0.05 ] #first for b_a, second for b_g in degree
        initSigmaC: [ 1000., 10. ] #cb in m, cd in m/s

      IMUPreintegrator:
        accelerometerSigma: 3e-8
        integrationSigma: 1e-5
        gyroscopeSigma: 52e-4 # 52e-5
        biasAccSigma: 0.000167 # 4e-4
        biasOmegaSigma: 87e-5 # 87e-5
        biasAccOmegaInt: 0.00001 # 0.00001

      Graph:
        publishResiduals: false
        publishResidualsOnline: false
        addIMUFactor: true
        IMUMeasurementFrequency: 100  #
        addGPPriorFactor: true
        fullGPPrior: false
        gpType: 'WNOJ'  # 'WNOA'
        addGPInterpolatedFactor: true
        addEstimatedVarianceAfterInit: false

        AutoDiffNormalFactor: true
        AutoDiffGPInterpolatedFactor: true
        AutoDiffGPMotionPriorFactor: false
        GPInterpolatedFactorCalcJacobian: true

        StateMeasSyncUpperBound: 0.02
        StateMeasSyncLowerBound: -0.02
        addMMFactor: false
        addConstDriftFactor: false

        noiseModelClockFactor: "huber"
        robustParamClockFactor: 10.
        constDriftStd: 0.5
        constBiasStd: .1
        motionModelStd: 1.
        angularRateStd: 0.1
        magnetometerStd: 0.01

        NoOptimizationWhileNoMeasurement: false
        NoOptimizationNearZeroVelocity: false
        VoteNearZeroVelocity: 0.1 # 20%
        NoOptimizationAfterStates: 0

      Integrators: [ "GNSSLCIntegrator", ]   # ["PohangGNSSLCIntegrator", "LIOIntegrator", "BeaconIntegrator"]

      Optimizer:
        #undefined, BatchFixedLag, IncrementalFixedLag
        smootherType: 'IncrementalFixedLag'
        smootherLag: .5 #marginalization threshold
        #QcGPWNOJInterpolator: 1000.
        #QcGPWNOJMotionPrior: 10000.
        QcGPWNOJInterpolatorFull: [ 10000., 100000., 100000., 100000., 100000., 100000. ]
        QcGPWNOJMotionPriorFull: [ 100000., 100000., 100000., 100000., 100000., 100000. ]
        #QcGPWNOJInterpolatorFull: [ 1000., 1000., 1000., 10000., 10000., 10000. ]
        #QcGPWNOJMotionPriorFull: [ 1000., 1000., 1000., 10000., 10000., 10000. ]
        #QcGPWNOAInterpolator: 0.5
        #QcGPWNOAMotionPrior: 0.5
        QcGPWNOAInterpolatorFull: [ 1.666669, 1.666669, 1.666669, 16.66669, 16.66669, 16.66669 ]
        QcGPWNOAMotionPriorFull: [ 1.666669, 1.666669, 1.666669, 16.66669, 16.66669, 16.66669 ]
        #QcGPWNOAInterpolatorFull: [ .16691, .16691, .16691, 1.666669, 1.666669, 1.666669 ]
        #QcGPWNOAMotionPriorFull: [ .16691, .16691, .16691, 1.666669, 1.666669, 1.666669 ]

